site_name: mnx
site_description: A Python toolkit for crystallographic structures and dynamical matrices.
site_author: Manex Alkorta
site_url: https://ManexAlkorta.github.io/mnx/

# 1. Look and Feel
theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.sections
    - content.code.copy

# 2. Extensions for Math and Code
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - arithmatex:
      generic: true

# 3. The "Magic" Plugin (Reads your Python Docstrings)
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('./src/')
          options:
            show_root_heading: true
            show_source: true

# 4. Navigation Structure
nav:
  - Home: README.md  # We will link your README here